# Generated by Django 2.2.3 on 2019-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190710_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
