# Generated by Django 2.2.3 on 2019-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name2',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(verbose_name=['%d/%m/%Y %H:%M:%S']),
        ),
    ]
